// <auto-generated />
using System;
using Hospitalidée_CRM_Back_End.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hospitalidée_CRM_Back_End.Migrations
{
    [DbContext(typeof(UniteLegaleContext))]
    [Migration("20201209160800_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Hospitalidée_CRM_Back_End.Models.Etablissement", b =>
                {
                    b.Property<Guid>("etablissementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("activite_principale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code_postal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("denomination_usuelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("libelle_commune")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("libelle_voie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numero_voie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("siret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type_voie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("unite_legaleuniteLegaleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("etablissementId");

                    b.HasIndex("unite_legaleuniteLegaleId");

                    b.ToTable("Etablissement");
                });

            modelBuilder.Entity("Hospitalidée_CRM_Back_End.Models.UniteLegale", b =>
                {
                    b.Property<Guid>("uniteLegaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("denomination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomenclature_activité_principale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenom_usuel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("siren")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("uniteLegaleId");

                    b.ToTable("UniteLegale");
                });

            modelBuilder.Entity("Hospitalidée_CRM_Back_End.Models.Etablissement", b =>
                {
                    b.HasOne("Hospitalidée_CRM_Back_End.Models.UniteLegale", "unite_legale")
                        .WithMany()
                        .HasForeignKey("unite_legaleuniteLegaleId");

                    b.Navigation("unite_legale");
                });
#pragma warning restore 612, 618
        }
    }
}
